import { useState } from 'react';
import { Download, BarChart2, Clock, Users, CreditCard, X } from 'lucide-react';

const REPORT_CARDS = [
  { id: 'attendance', icon: Clock,    label: 'Attendance Report',  desc: 'Daily, weekly, monthly attendance summaries with shift breakdown.', color: '#0d7470', bg: '#f0fdfa' },
  { id: 'workforce',  icon: Users,    label: 'Workforce Report',   desc: 'Headcount, department distribution, attrition, and hiring trends.', color: '#2563eb', bg: '#eff6ff' },
  { id: 'payroll',    icon: CreditCard, label: 'Payroll Report',   desc: 'Payroll summary, PF, TDS, and net disbursements by department.', color: '#6366f1', bg: '#f5f3ff' },
  { id: 'leave',      icon: BarChart2, label: 'Leave & Absence Report', desc: 'Leave utilization, balance summary, and absence patterns.', color: '#d97706', bg: '#fffbeb' },
];

const RECENT = [
  { name: 'Attendance_June_2026.xlsx',   type: 'Attendance', generated: '2026-06-25', size: '128 KB', by: 'Priya Mehta' },
  { name: 'Payroll_May_2026.pdf',        type: 'Payroll',    generated: '2026-06-01', size: '84 KB',  by: 'Priya Mehta' },
  { name: 'Workforce_Q2_2026.xlsx',      type: 'Workforce',  generated: '2026-05-30', size: '245 KB', by: 'Priya Mehta' },
  { name: 'Leave_Summary_2026.pdf',      type: 'Leave',      generated: '2026-05-22', size: '56 KB',  by: 'Priya Mehta' },
  { name: 'Attendance_May_2026.xlsx',    type: 'Attendance', generated: '2026-05-28', size: '119 KB', by: 'Priya Mehta' },
];

const TYPE_COLORS: Record<string, { bg: string; color: string }> = {
  Attendance: { bg: '#f0fdfa', color: '#0d7470' },
  Payroll:    { bg: '#f5f3ff', color: '#6366f1' },
  Workforce:  { bg: '#eff6ff', color: '#2563eb' },
  Leave:      { bg: '#fffbeb', color: '#d97706' },
};

export default function CAReportsPage() {
  const [showModal, setShowModal] = useState(false);
  const [selectedReport, setSelectedReport] = useState('');
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo]     = useState('');
  const [format, setFormat]     = useState<'xlsx' | 'pdf'>('xlsx');

  const openModal = (id: string) => { setSelectedReport(id); setShowModal(true); };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      <div>
        <h1 style={{ fontSize: '20px', fontWeight: 700, color: '#0f172a' }}>Reports</h1>
        <p style={{ fontSize: '12px', color: '#64748b', marginTop: '2px' }}>Generate and download custom reports for attendance, payroll, and workforce.</p>
      </div>

      {/* Report cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '14px' }}>
        {REPORT_CARDS.map(({ id, icon: Icon, label, desc, color, bg }) => (
          <div key={id} style={{ backgroundColor: 'white', borderRadius: '10px', border: '1px solid #e2e8f0', padding: '18px 18px' }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', gap: '12px' }}>
              <div style={{ width: '38px', height: '38px', borderRadius: '10px', backgroundColor: bg, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                <Icon size={18} color={color} />
              </div>
              <div style={{ flex: 1 }}>
                <p style={{ fontSize: '13px', fontWeight: 700, color: '#0f172a' }}>{label}</p>
                <p style={{ fontSize: '11px', color: '#64748b', marginTop: '4px', lineHeight: 1.5 }}>{desc}</p>
                <button onClick={() => openModal(id)} style={{ display: 'flex', alignItems: 'center', gap: '5px', marginTop: '12px', padding: '6px 14px', borderRadius: '7px', backgroundColor: color, border: 'none', color: 'white', fontSize: '11px', fontWeight: 600, cursor: 'pointer', fontFamily: 'Inter, sans-serif' }}>
                  <Download size={11} /> Generate Report
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Recent downloads */}
      <div style={{ backgroundColor: 'white', borderRadius: '10px', border: '1px solid #e2e8f0', overflow: 'hidden' }}>
        <div style={{ padding: '14px 18px', borderBottom: '1px solid #e2e8f0' }}>
          <h3 style={{ fontSize: '13px', fontWeight: 700, color: '#0f172a' }}>Recent Downloads</h3>
        </div>
        <table style={{ width: '100%', borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ backgroundColor: '#f8fafc' }}>
              {['File Name', 'Type', 'Generated On', 'Size', 'Generated By', ''].map((h) => (
                <th key={h} style={{ padding: '10px 16px', textAlign: 'left', fontSize: '10px', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.5px', borderBottom: '1px solid #e2e8f0' }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {RECENT.map((r, i) => {
              const tc = TYPE_COLORS[r.type]!;
              return (
                <tr key={r.name} style={{ backgroundColor: i % 2 === 0 ? 'white' : '#fafafa' }}>
                  <td style={{ padding: '11px 16px', fontSize: '12px', fontWeight: 600, color: '#0f172a', borderBottom: '1px solid #f1f5f9' }}>{r.name}</td>
                  <td style={{ padding: '11px 16px', borderBottom: '1px solid #f1f5f9' }}>
                    <span style={{ padding: '2px 8px', borderRadius: '4px', fontSize: '10px', fontWeight: 600, backgroundColor: tc.bg, color: tc.color }}>{r.type}</span>
                  </td>
                  <td style={{ padding: '11px 16px', fontSize: '11px', color: '#64748b', borderBottom: '1px solid #f1f5f9' }}>{new Date(r.generated).toLocaleDateString('en-IN', { month: 'short', day: 'numeric', year: 'numeric' })}</td>
                  <td style={{ padding: '11px 16px', fontSize: '11px', color: '#64748b', borderBottom: '1px solid #f1f5f9' }}>{r.size}</td>
                  <td style={{ padding: '11px 16px', fontSize: '11px', color: '#374151', borderBottom: '1px solid #f1f5f9' }}>{r.by}</td>
                  <td style={{ padding: '11px 16px', borderBottom: '1px solid #f1f5f9' }}>
                    <button style={{ background: 'none', border: 'none', cursor: 'pointer', color: '#0d7470', display: 'flex', alignItems: 'center', gap: '4px' }}>
                      <Download size={12} /><span style={{ fontSize: '11px', fontWeight: 600 }}>Download</span>
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Generate modal */}
      {showModal && (
        <div style={{ position: 'fixed', inset: 0, zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <div onClick={() => setShowModal(false)} style={{ position: 'absolute', inset: 0, backgroundColor: 'rgba(0,0,0,0.3)' }} />
          <div style={{ position: 'relative', backgroundColor: 'white', borderRadius: '12px', border: '1px solid #e2e8f0', padding: '24px', width: '380px', boxShadow: '0 8px 32px rgba(0,0,0,0.12)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '18px' }}>
              <h2 style={{ fontSize: '15px', fontWeight: 700, color: '#0f172a' }}>Generate Report</h2>
              <button onClick={() => setShowModal(false)} style={{ background: 'none', border: 'none', cursor: 'pointer' }}><X size={16} color="#64748b" /></button>
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#374151', marginBottom: '5px' }}>Report Type</label>
                <select value={selectedReport} onChange={(e) => setSelectedReport(e.target.value)} style={{ width: '100%', padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '7px', fontSize: '12px', outline: 'none', fontFamily: 'Inter, sans-serif', color: '#374151', backgroundColor: 'white' }}>
                  {REPORT_CARDS.map((r) => <option key={r.id} value={r.id}>{r.label}</option>)}
                </select>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '10px' }}>
                <div>
                  <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#374151', marginBottom: '5px' }}>Date From</label>
                  <input type="date" value={dateFrom} onChange={(e) => setDateFrom(e.target.value)} style={{ width: '100%', padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '7px', fontSize: '12px', outline: 'none', fontFamily: 'Inter, sans-serif', color: '#374151', boxSizing: 'border-box' }} />
                </div>
                <div>
                  <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#374151', marginBottom: '5px' }}>Date To</label>
                  <input type="date" value={dateTo} onChange={(e) => setDateTo(e.target.value)} style={{ width: '100%', padding: '8px 12px', border: '1px solid #e2e8f0', borderRadius: '7px', fontSize: '12px', outline: 'none', fontFamily: 'Inter, sans-serif', color: '#374151', boxSizing: 'border-box' }} />
                </div>
              </div>
              <div>
                <label style={{ display: 'block', fontSize: '12px', fontWeight: 600, color: '#374151', marginBottom: '5px' }}>Format</label>
                <div style={{ display: 'flex', gap: '8px' }}>
                  {(['xlsx', 'pdf'] as const).map((f) => (
                    <button key={f} onClick={() => setFormat(f)} style={{ flex: 1, padding: '8px', border: `1.5px solid ${format === f ? '#0d7470' : '#e2e8f0'}`, borderRadius: '7px', backgroundColor: format === f ? '#f0fdfa' : 'white', color: format === f ? '#0d7470' : '#374151', fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: 'Inter, sans-serif', textTransform: 'uppercase' }}>
                      {f}
                    </button>
                  ))}
                </div>
              </div>
            </div>
            <div style={{ display: 'flex', gap: '10px', marginTop: '20px' }}>
              <button onClick={() => setShowModal(false)} style={{ flex: 1, padding: '9px', border: '1px solid #e2e8f0', borderRadius: '8px', backgroundColor: 'white', color: '#374151', fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: 'Inter, sans-serif' }}>Cancel</button>
              <button onClick={() => setShowModal(false)} style={{ flex: 1, padding: '9px', border: 'none', borderRadius: '8px', backgroundColor: '#0d7470', color: 'white', fontSize: '12px', fontWeight: 600, cursor: 'pointer', fontFamily: 'Inter, sans-serif', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}>
                <Download size={13} /> Generate & Download
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
