import { useEffect, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { io, type Socket } from 'socket.io-client';
import { LifeBuoy, Loader2, MessageSquare, Plus, Send, X } from 'lucide-react';
import { supportApi, type SupportTicket } from '../../api/support';

type Comment = { id: string; body: string; createdAt: string; authorId?: { id?: string; name: string; role: string } };
const statusName: Record<string, string> = { PENDING:'Open', IN_PROGRESS:'In progress', RESOLVED:'Resolved', CLOSED:'Closed' };

export default function CASupportPage() {
  const [params, setParams] = useSearchParams(); const [tickets, setTickets] = useState<SupportTicket[]>([]); const [selected, setSelected] = useState<SupportTicket | null>(null); const [comments, setComments] = useState<Comment[]>([]); const [draft, setDraft] = useState(''); const [typing, setTyping] = useState(false); const [showNew, setShowNew] = useState(false); const [loading, setLoading] = useState(true); const [form, setForm] = useState({ category:'General', subject:'', description:'', priority:'MEDIUM' }); const socketRef = useRef<Socket | null>(null); const typingTimer = useRef<number | undefined>(undefined); const typingVisibilityTimer = useRef<number | undefined>(undefined);
  const load = async () => { setLoading(true); try { const { data } = await supportApi.getAll({ limit:'50' }); setTickets(data.tickets); } finally { setLoading(false); } };
  const open = async (ticket: SupportTicket) => { setSelected(ticket); setComments([]); const { data } = await supportApi.getComments(ticket.id); setComments(data.comments); };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const id = params.get('ticket'); if (!id) return; void supportApi.getOne(id).then(({ data }) => open(data)).finally(() => setParams({}, { replace:true })); }, [params, setParams]);
  useEffect(() => { if (!selected) return; const socket = io('/', { path:'/socket.io', auth:{ token:localStorage.getItem('accessToken') }, transports:['websocket', 'polling'] }); socketRef.current = socket; socket.on('connect', () => socket.emit('support:join', { ticketId:selected.id }, ({ ok }: { ok:boolean }) => { if (!ok) socket.disconnect(); })); socket.on('support:comment', ({ ticketId, comment }: { ticketId:string; comment:Comment }) => { if (ticketId === selected.id) setComments((old) => old.some((item) => item.id === comment.id) ? old : [...old, comment]); }); socket.on('support:typing', ({ ticketId, isTyping }: { ticketId:string; isTyping:boolean }) => { if (ticketId !== selected.id) return; window.clearTimeout(typingVisibilityTimer.current); setTyping(isTyping); if (isTyping) typingVisibilityTimer.current = window.setTimeout(() => setTyping(false), 1600); }); return () => { window.clearTimeout(typingTimer.current); window.clearTimeout(typingVisibilityTimer.current); socket.emit('support:typing', { ticketId:selected.id, isTyping:false }); socket.emit('support:leave', { ticketId:selected.id }); socket.disconnect(); socketRef.current = null; setTyping(false); }; }, [selected?.id]);
  useEffect(() => { const thread = Array.from(document.querySelectorAll<HTMLDivElement>('div')).find((element) => element.style.height === '280px' && element.style.overflowY === 'auto'); if (thread) thread.scrollTop = thread.scrollHeight; }, [comments, typing, selected?.id]);
  const changeDraft = (value: string) => { setDraft(value); if (!selected) return; socketRef.current?.emit('support:typing', { ticketId:selected.id, isTyping:Boolean(value) }); window.clearTimeout(typingTimer.current); typingTimer.current = window.setTimeout(() => socketRef.current?.emit('support:typing', { ticketId:selected.id, isTyping:false }), 900); };
  const send = async () => { if (!selected || !draft.trim()) return; const body = draft.trim(); setDraft(''); socketRef.current?.emit('support:typing', { ticketId:selected.id, isTyping:false }); try { const { data } = await supportApi.addComment(selected.id, body); setComments((old) => old.some((item) => item.id === data.id) ? old : [...old, data]); } catch { setDraft(body); } };
  const create = async () => { if (!form.subject.trim() || !form.description.trim()) return; await supportApi.create(form); setShowNew(false); setForm({ category:'General',subject:'',description:'',priority:'MEDIUM' }); await load(); };
  return <div style={{display:'flex',flexDirection:'column',gap:18}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h1 style={{fontSize:20,margin:0}}>Help & Support</h1><p style={{fontSize:12,color:'#64748b'}}>Track support requests and chat with the support team.</p></div><button style={primary} onClick={() => setShowNew(true)}><Plus size={15}/> New ticket</button></div><div style={card}>{loading?<div style={{padding:40,textAlign:'center'}}><Loader2/></div>:tickets.length?tickets.map((ticket)=><button key={ticket.id} onClick={() => void open(ticket)} style={{width:'100%',textAlign:'left',display:'flex',gap:12,padding:'14px 16px',border:0,borderBottom:'1px solid #f1f5f9',background:'white',cursor:'pointer'}}><MessageSquare size={16} color="#0d7470"/><span style={{flex:1}}><b style={{display:'block',fontSize:13}}>{ticket.subject}</b><small style={{color:'#64748b'}}>{ticket.ticketNo} · {ticket.category}</small></span><small style={{color:'#0d7470',fontWeight:700}}>{statusName[ticket.status]}</small></button>):<div style={{padding:45,textAlign:'center',color:'#64748b'}}><LifeBuoy/><p>No tickets yet.</p></div>}</div>
  {showNew&&<Modal onClose={()=>setShowNew(false)}><h2>Submit support ticket</h2><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} style={input}><option>General</option><option>Payroll</option><option>Attendance</option><option>Account</option><option>Bug report</option></select><input placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} style={input}/><textarea placeholder="Describe the issue" rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} style={input}/><button style={primary} onClick={()=>void create()}>Submit ticket</button></Modal>}
  {selected&&<Modal onClose={()=>setSelected(null)}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h2 style={{margin:0,fontSize:16}}>{selected.subject}</h2><small style={{color:'#64748b'}}>{selected.ticketNo} · {statusName[selected.status]}</small></div></div><p style={{fontSize:13,lineHeight:1.5,background:'#f8fafc',padding:10,borderRadius:8}}>{selected.description}</p><h3 style={{fontSize:13}}>Conversation</h3><div style={{height:280,overflowY:'auto',display:'flex',flexDirection:'column',gap:8}}>{comments.map((comment)=><div key={comment.id} style={{padding:'9px 11px',background:comment.authorId?.role==='SUPER_ADMIN'?'#eff6ff':'#f0fdfa',borderRadius:10,maxWidth:'84%',alignSelf:comment.authorId?.role==='SUPER_ADMIN'?'flex-start':'flex-end'}}><b style={{fontSize:11}}>{comment.authorId?.name??'User'}</b><p style={{fontSize:12,margin:'3px 0',whiteSpace:'pre-wrap'}}>{comment.body}</p><small style={{fontSize:10,color:'#64748b'}}>{new Date(comment.createdAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</small></div>)}</div>{typing&&<p style={{margin:'7px 0 0',fontSize:11,color:'#0d7470',fontStyle:'italic'}}>Support is typing…</p>}<div style={{display:'flex',gap:8,marginTop:10}}><input value={draft} onChange={e=>changeDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send();}}} placeholder="Write a message…" style={{...input,flex:1}}/><button style={primary} onClick={()=>void send()}><Send size={15}/></button></div></Modal>}</div>;
}
function Modal({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <div style={{position:'fixed',inset:0,zIndex:1000,display:'grid',placeItems:'center',background:'rgba(15,23,42,.48)',padding:20}}><div style={{width:'100%',maxWidth:700,maxHeight:'88vh',overflow:'hidden',background:'white',borderRadius:16,boxShadow:'0 20px 60px rgba(15,23,42,.2)',display:'flex',flexDirection:'column'}}><button onClick={onClose} style={{alignSelf:'flex-end',border:0,background:'transparent',cursor:'pointer',padding:'14px 16px 4px',color:'#64748b',flexShrink:0}}><X size={18}/></button><div style={{padding:'0 24px 24px',display:'flex',flexDirection:'column',gap:12,overflow:'hidden',minHeight:0}}>{children}</div></div></div>}
const card:React.CSSProperties={background:'white',border:'1px solid #e2e8f0',borderRadius:12,overflow:'hidden'}; const primary:React.CSSProperties={display:'inline-flex',alignItems:'center',justifyContent:'center',gap:6,padding:'9px 13px',border:0,borderRadius:8,background:'#0d7470',color:'white',fontWeight:700,cursor:'pointer'}; const input:React.CSSProperties={width:'100%',boxSizing:'border-box',padding:9,border:'1px solid #cbd5e1',borderRadius:8,fontSize:13};
