import { useEffect, useState } from 'react';
import { LifeBuoy, Loader2, MessageSquare, Plus, Send, X } from 'lucide-react';
import { supportApi, type SupportTicket } from '../../api/support';
import { extractError } from '../../utils/errorUtils';

const labels: Record<string, string> = { PENDING: 'Open', IN_PROGRESS: 'In Progress', RESOLVED: 'Resolved', CLOSED: 'Closed' };
const colors: Record<string, { background: string; color: string }> = { PENDING: { background: '#fef9c3', color: '#a16207' }, IN_PROGRESS: { background: '#dbeafe', color: '#1d4ed8' }, RESOLVED: { background: '#dcfce7', color: '#15803d' }, CLOSED: { background: '#f1f5f9', color: '#475569' } };

export default function CASupportPage() {
  const [tickets, setTickets] = useState<SupportTicket[]>([]); const [selected, setSelected] = useState<SupportTicket | null>(null); const [comments, setComments] = useState<any[]>([]); const [comment, setComment] = useState(''); const [showNew, setShowNew] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState({ category: 'General', subject: '', description: '', priority: 'MEDIUM' });
  const load = async () => { setLoading(true); try { const { data } = await supportApi.getAll({ limit: '50' }); setTickets(data.tickets); } catch (e) { setError(extractError(e, 'Unable to load support tickets')); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const open = async (ticket: SupportTicket) => { setSelected(ticket); const { data } = await supportApi.getComments(ticket.id); setComments(data.comments); };
  const create = async () => { if (!form.subject.trim() || !form.description.trim()) return; try { await supportApi.create(form); setShowNew(false); setForm({ category: 'General', subject: '', description: '', priority: 'MEDIUM' }); await load(); } catch (e) { setError(extractError(e, 'Unable to submit ticket')); } };
  const reply = async () => { if (!selected || !comment.trim()) return; await supportApi.addComment(selected.id, comment.trim()); setComment(''); const { data } = await supportApi.getComments(selected.id); setComments(data.comments); };
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}><div><h1 style={{ fontSize: 20, fontWeight: 700, color: '#0f172a' }}>Help & Support</h1><p style={{ fontSize: 12, color: '#64748b', marginTop: 3 }}>Submit and track support requests for your company.</p></div><button onClick={() => setShowNew(true)} style={{ display: 'flex', gap: 6, alignItems: 'center', padding: '8px 13px', border: 0, borderRadius: 8, color: 'white', background: '#0d7470', cursor: 'pointer', fontWeight: 600 }}><Plus size={14} /> New Ticket</button></div>
    {error && <div style={{ padding: 10, borderRadius: 8, background: '#fef2f2', color: '#b91c1c', fontSize: 12 }}>{error}</div>}
    <div style={{ background: 'white', border: '1px solid #e2e8f0', borderRadius: 12, overflow: 'hidden' }}>{loading ? <div style={{ padding: 50, textAlign: 'center' }}><Loader2 size={20} color="#0d7470" /></div> : tickets.length === 0 ? <div style={{ padding: 50, textAlign: 'center', color: '#64748b' }}><LifeBuoy size={30} style={{ margin: '0 auto 8px' }} /><p>No support tickets yet.</p></div> : tickets.map((t) => { const c = colors[t.status] ?? colors.PENDING; return <button key={t.id} onClick={() => void open(t)} style={{ width: '100%', display: 'flex', alignItems: 'center', gap: 14, padding: '15px 18px', border: 0, borderBottom: '1px solid #f1f5f9', background: 'white', textAlign: 'left', cursor: 'pointer' }}><MessageSquare size={16} color="#0d7470" /><span style={{ flex: 1 }}><strong style={{ display: 'block', fontSize: 13, color: '#0f172a' }}>{t.subject}</strong><small style={{ color: '#64748b' }}>{t.ticketNo} · {t.category}</small></span><span style={{ padding: '4px 9px', borderRadius: 20, background: c.background, color: c.color, fontSize: 11, fontWeight: 700 }}>{labels[t.status]}</span></button>; })}</div>
    {showNew && <div style={{ position: 'fixed', inset: 0, zIndex: 100, background: 'rgba(15,23,42,.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}><div style={{ width: '100%', maxWidth: 520, background: 'white', borderRadius: 14, padding: 22 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><h2 style={{ fontSize: 16 }}>Submit Support Ticket</h2><button onClick={() => setShowNew(false)} style={{ border: 0, background: 'none', cursor: 'pointer' }}><X size={18} /></button></div><div style={{ display: 'grid', gap: 11, marginTop: 18 }}><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} style={{ padding: 9, border: '1px solid #e2e8f0', borderRadius: 7 }}><option>General</option><option>Payroll</option><option>Attendance</option><option>Leave</option><option>Account</option><option>Bug Report</option><option>Feature Request</option></select><input placeholder="Subject" value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} style={{ padding: 9, border: '1px solid #e2e8f0', borderRadius: 7 }} /><textarea placeholder="Describe the issue..." rows={6} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} style={{ padding: 9, border: '1px solid #e2e8f0', borderRadius: 7, resize: 'vertical' }} /><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} style={{ padding: 9, border: '1px solid #e2e8f0', borderRadius: 7 }}><option value="LOW">Low priority</option><option value="MEDIUM">Medium priority</option><option value="HIGH">High priority</option><option value="CRITICAL">Critical priority</option></select><button onClick={() => void create()} style={{ padding: 10, border: 0, borderRadius: 7, background: '#0d7470', color: 'white', fontWeight: 700, cursor: 'pointer' }}>Submit Ticket</button></div></div></div>}
    {selected && <div style={{ position: 'fixed', inset: 0, zIndex: 100, background: 'rgba(15,23,42,.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}><div style={{ width: '100%', maxWidth: 560, maxHeight: '85vh', overflow: 'auto', background: 'white', borderRadius: 14, padding: 22 }}><div style={{ display: 'flex', justifyContent: 'space-between' }}><div><h2 style={{ fontSize: 16 }}>{selected.subject}</h2><small style={{ color: '#64748b' }}>{selected.ticketNo} · {labels[selected.status]}</small></div><button onClick={() => setSelected(null)} style={{ border: 0, background: 'none', cursor: 'pointer' }}><X size={18} /></button></div><p style={{ marginTop: 18, padding: 12, background: '#f8fafc', borderRadius: 8, fontSize: 13, lineHeight: 1.6 }}>{selected.description}</p><h3 style={{ fontSize: 13, margin: '18px 0 10px' }}>Conversation</h3>{comments.map((c) => <div key={c.id} style={{ padding: 10, borderBottom: '1px solid #f1f5f9', fontSize: 12 }}><strong>{c.authorId?.name ?? 'User'}</strong><p style={{ marginTop: 4, color: '#475569' }}>{c.body}</p></div>)}<div style={{ display: 'flex', gap: 8, marginTop: 12 }}><input value={comment} onChange={(e) => setComment(e.target.value)} placeholder="Write a reply..." style={{ flex: 1, padding: 9, border: '1px solid #e2e8f0', borderRadius: 7 }} /><button onClick={() => void reply()} style={{ border: 0, borderRadius: 7, background: '#0d7470', color: 'white', padding: '0 12px', cursor: 'pointer' }}><Send size={15} /></button></div></div></div>}
  </div>;
}
