import { useEffect, useState } from 'react';
import { paymentsApi, type Payment } from '../../api/payments';
import { companiesApi, type Company } from '../../api/companies';
import { extractError } from '../../utils/errorUtils';

const statusStyle: Record<string, React.CSSProperties> = { PAID: { color: '#15803d', background: '#dcfce7' }, PENDING: { color: '#a16207', background: '#fef9c3' }, FAILED: { color: '#b91c1c', background: '#fee2e2' }, REFUNDED: { color: '#7c3aed', background: '#f3e8ff' }, CANCELLED: { color: '#475569', background: '#f1f5f9' } };
export default function PaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]); const [companies, setCompanies] = useState<Company[]>([]); const [source, setSource] = useState('ALL'); const [status, setStatus] = useState('ALL'); const [error, setError] = useState('');
  const [form, setForm] = useState({ companyId: '', amount: '', status: 'PENDING' as 'PENDING' | 'PAID', reference: '', notes: '' });
  const load = () => paymentsApi.getAll({ source, status }).then((r) => setPayments(r.data.payments)).catch((e) => setError(extractError(e, 'Could not load payments')));
  useEffect(() => { load(); }, [source, status]);
  useEffect(() => { companiesApi.getAll({ limit: '100' }).then((r) => setCompanies(r.data.companies)).catch(() => {}); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); try { await paymentsApi.createOffline({ companyId: form.companyId, amount: form.amount ? Number(form.amount) : undefined, status: form.status, reference: form.reference || undefined, notes: form.notes || undefined }); setForm({ companyId: '', amount: '', status: 'PENDING', reference: '', notes: '' }); load(); } catch (e) { setError(extractError(e, 'Could not record payment')); } };
  return <div style={{ padding: 28 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 24 }}><div><h1 style={{ fontSize: 22, color: '#0f172a' }}>Payments</h1><p style={{ color: '#64748b', fontSize: 13 }}>Online Razorpay and offline payment audit trail.</p></div></div>{error && <p style={{ color: '#b91c1c' }}>{error}</p>}
    <form onSubmit={submit} style={{ padding: 16, border: '1px solid #e2e8f0', borderRadius: 10, display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 20 }}><select required value={form.companyId} onChange={e => setForm({ ...form, companyId: e.target.value })}><option value="">Select company</option>{companies.map(c => <option value={c.id} key={c.id}>{c.name}</option>)}</select><input placeholder="Amount (optional)" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })}/><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value as any })}><option value="PENDING">Pending</option><option value="PAID">Paid</option></select><input placeholder="Receipt / reference" value={form.reference} onChange={e => setForm({ ...form, reference: e.target.value })}/><button type="submit">Record offline payment</button></form>
    <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}><select value={source} onChange={e => setSource(e.target.value)}><option>ALL</option><option>OFFLINE</option><option>RAZORPAY</option></select><select value={status} onChange={e => setStatus(e.target.value)}><option>ALL</option>{['PENDING','PAID','FAILED','CANCELLED','REFUNDED'].map(s => <option key={s}>{s}</option>)}</select></div>
    <table style={{ width: '100%', borderCollapse: 'collapse', background: 'white' }}><thead><tr>{['Company','Source','Plan','Amount','Status','Reference','Date'].map(h => <th key={h} style={{ textAlign: 'left', padding: 12, borderBottom: '1px solid #e2e8f0' }}>{h}</th>)}</tr></thead><tbody>{payments.map(p => <tr key={p.id}><td style={{ padding: 12 }}>{p.company?.name || 'Pending checkout / legacy'}</td><td>{p.source}</td><td>{p.plan}</td><td>₹{p.amount.toLocaleString('en-IN')}</td><td>{p.source === 'OFFLINE' ? <select value={p.status} onChange={async e => { try { await paymentsApi.update(p.id, { status: e.target.value as any }); load(); } catch (err) { setError(extractError(err, 'Could not update payment')); } }}><option>PENDING</option><option>PAID</option><option>FAILED</option><option>CANCELLED</option><option>REFUNDED</option></select> : <span style={{ padding: '3px 8px', borderRadius: 12, fontSize: 12, ...statusStyle[p.status] }}>{p.status}</span>}</td><td>{p.reference || '—'}</td><td>{new Date(p.paidAt || p.createdAt).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div>;
}
