export const PERMISSIONS = {
  DASHBOARD: 'Dashboard',
  ATTENDANCE_VIEW: 'Attendance — View',
  ATTENDANCE_EDIT: 'Attendance — Edit',
  WORKFORCE_VIEW: 'Workforce — View',
  WORKFORCE_EDIT: 'Workforce — Add/Edit',
  PAYROLL_VIEW: 'Payroll — View',
  PAYROLL_PROCESS: 'Payroll — Process',
  APPROVALS_VIEW: 'Approvals — View',
  APPROVALS_ACTION: 'Approvals — Action',
  REPORTS_VIEW: 'Reports — View',
  REPORTS_DOWNLOAD: 'Reports — Download',
  SETTINGS_COMPANY: 'Settings — Company',
  SETTINGS_ROLES: 'Settings — Roles',
  SETTINGS_WORKFLOWS: 'Settings — Workflows',
} as const;

export const DEFAULT_PERMISSIONS: Record<string, string[]> = {
  COMPANY_ADMIN: ['*'],
  HR: [PERMISSIONS.DASHBOARD, PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_EDIT, PERMISSIONS.WORKFORCE_VIEW, PERMISSIONS.WORKFORCE_EDIT, PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_ACTION, PERMISSIONS.REPORTS_VIEW],
  MANAGER: [PERMISSIONS.DASHBOARD, PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.WORKFORCE_VIEW, PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.REPORTS_VIEW],
  SUPERVISOR: [PERMISSIONS.DASHBOARD, PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.WORKFORCE_VIEW, PERMISSIONS.APPROVALS_VIEW],
  FINANCE: [PERMISSIONS.DASHBOARD, PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_PROCESS, PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_DOWNLOAD],
  EMPLOYEE: [PERMISSIONS.DASHBOARD],
};

export const canUsePermission = (role: string, permission: string, configured?: boolean): boolean =>
  configured ?? (DEFAULT_PERMISSIONS[role]?.includes('*') || DEFAULT_PERMISSIONS[role]?.includes(permission) || false);
