export const qk = {
  hr: {
    employees:         (p?: object) => ['hr', 'employees', p],
    employee:          (id: string) => ['hr', 'employee', id],
    departments:       ()           => ['hr', 'departments'],
    attendance:        ()           => ['hr', 'attendance', 'overview'],
    attendanceRecords: (p?: object) => ['hr', 'attendance', 'records', p],
    leaves:            (p?: object) => ['hr', 'leaves', p],
    approvals:         (p?: object) => ['hr', 'approvals', p],
    salary:            (p?: object) => ['hr', 'salary', p],
    payslips:          (p?: object) => ['hr', 'payslips', p],
    shifts:            (p?: object) => ['hr', 'shifts', p],
    documents:         (p?: object) => ['hr', 'documents', p],
  },
  ca: {
    dashboard:       ()                       => ['ca', 'dashboard'],
    users:           (p?: object)             => ['ca', 'users', p],
    departments:     ()                       => ['ca', 'departments'],
    company:         ()                       => ['ca', 'company'],
    modules:         ()                       => ['ca', 'modules'],
    activity:        (p?: object)             => ['ca', 'activity', p],
    rolePermissions: ()                       => ['ca', 'rolePermissions'],
    workflows:       ()                       => ['ca', 'workflows'],
    report:          (type: string, p?: object) => ['ca', 'report', type, p],
  },
  emp: {
    profile:     ()           => ['emp', 'profile'],
    attendance:  (p?: object) => ['emp', 'attendance', p],
    todayStatus: ()           => ['emp', 'attendance', 'today'],
    leaves:      ()           => ['emp', 'leaves'],
    payslips:    ()           => ['emp', 'payslips'],
    expenses:    ()           => ['emp', 'expenses'],
    documents:   (p?: object) => ['emp', 'documents', p],
  },
  finance: {
    attendance: ()                        => ['finance', 'attendance'],
    employees:  (p?: object)              => ['finance', 'employees', p],
    salary:     (p?: object)              => ['finance', 'salary', p],
    payslips:   (p?: object)              => ['finance', 'payslips', p],
    expenses:   (p?: object)              => ['finance', 'expenses', p],
    report:     (type: string, p?: object) => ['finance', 'report', type, p],
  },
  sa: {
    companies:     (p?: object) => ['sa', 'companies', p],
    plans:         ()           => ['sa', 'plans'],
    subscriptions: (p?: object) => ['sa', 'subscriptions', p],
    activity:      (p?: object) => ['sa', 'activity', p],
    support:       (p?: object) => ['sa', 'support', p],
    modules:       ()           => ['sa', 'modules'],
  },
  mgr: {
    workforce:  (p?: object)              => ['mgr', 'workforce', p],
    attendance: (p?: object)              => ['mgr', 'attendance', p],
    approvals:  (p?: object)              => ['mgr', 'approvals', p],
    report:     (type: string, p?: object) => ['mgr', 'report', type, p],
  },
  sup: {
    workforce:  (p?: object) => ['sup', 'workforce', p],
    attendance: (p?: object) => ['sup', 'attendance', p],
    shifts:     (p?: object) => ['sup', 'shifts', p],
    approvals:  (p?: object) => ['sup', 'approvals', p],
  },
} as const;
